# Generated by Django 4.0.5 on 2022-06-30 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=200)),
                ('question_des', models.CharField(max_length=5000)),
                ('question_diff', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=1000)),
                ('user_pass', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_testcases', models.CharField(max_length=1000)),
                ('otput_testcases', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.question')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submission_status', models.CharField(max_length=10)),
                ('submission_date', models.DateTimeField(verbose_name='date submitted')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.user')),
            ],
        ),
    ]
